// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoKsoT11nq1ozGa0sqLzMIchnI7tAc_nc',
    appId: '1:221549700997:web:66595769b986a10bc746ec',
    messagingSenderId: '221549700997',
    projectId: 'automate-7d482',
    authDomain: 'automate-7d482.firebaseapp.com',
    storageBucket: 'automate-7d482.firebasestorage.app',
    measurementId: 'G-JRPNDC98G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQRj2IG9uno-pNm6AjB2WtgCwm0jOSgB4',
    appId: '1:221549700997:android:4a5fa0b7bed30ba9c746ec',
    messagingSenderId: '221549700997',
    projectId: 'automate-7d482',
    storageBucket: 'automate-7d482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvAHRv0wTlsl4Z0Vcab5Ax9JNk5WXU3fA',
    appId: '1:221549700997:ios:2d81a935e49a544fc746ec',
    messagingSenderId: '221549700997',
    projectId: 'automate-7d482',
    storageBucket: 'automate-7d482.firebasestorage.app',
    iosBundleId: 'com.example.automateApplication',
  );
}
